version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_c
    restart: always
    ports:
      - "3000:80"
    networks:
      - audit
    volumes:
      - ./frontend:/app/frontend

  mysql_db:
    image: mysql
    container_name: mysql_c
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: audit
      MYSQL_USER: bong
      MYSQL_PASSWORD: bong
    ports:
      - "3307:3306"
    networks:
      - audit
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    container_name: backend_c
    ports:
      - "8000:8000"
    # env_file:
    #   - ./backend/.env
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=bong
      - MYSQL_PASSWORD=bong
      - MYSQL_DB=audit
    networks:
      - audit
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/backend/uploads

networks:
  audit:
    driver: bridge

volumes:
  mysql_data:
  backend_uploads:
